# Generated by Django 6.0.6 on 2026-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
